[versions]
hamcrest = "3.0"
jgrapht = "1.5.2"
junit5 = "5.13.0"
kotlin-jvm = "2.1.21"
sonarqube-plugin = "6.2.0.5505"

[libraries]
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
jgrapht-core = { group = "org.jgrapht", name = "jgrapht-core", version.ref = "jgrapht" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
sonarqube-plugin = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }
